// <auto-generated />
using System;
using CivicOps.Modules.Requests.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CivicOps.Modules.Requests.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RequestsDbContext))]
    [Migration("20260729173938_AddRequestAuditAndOutbox")]
    partial class AddRequestAuditAndOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("requests")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CivicOps.Modules.Requests.Domain.Requests.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("DueDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date_utc");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("protocol_number");

                    b.Property<Guid?>("ResponsibleUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_administrative_requests_tenant_id");

                    b.HasIndex("TenantId", "CreatedAtUtc")
                        .HasDatabaseName("ix_administrative_requests_tenant_created_at");

                    b.HasIndex("TenantId", "DueDateUtc")
                        .HasDatabaseName("ix_administrative_requests_tenant_due_date");

                    b.HasIndex("TenantId", "ProtocolNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_administrative_requests_tenant_protocol");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_administrative_requests_tenant_status_created_at");

                    b.HasIndex("TenantId", "ResponsibleUserId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_administrative_requests_tenant_responsible_status_created_at");

                    b.ToTable("administrative_requests", "requests");
                });

            modelBuilder.Entity("CivicOps.Modules.Requests.Domain.Requests.RequestComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "RequestId", "CreatedAtUtc")
                        .HasDatabaseName("ix_request_comments_tenant_request_created_at");

                    b.ToTable("request_comments", "requests");
                });

            modelBuilder.Entity("CivicOps.Modules.Requests.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_tenant_occurred_at");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc", "OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_pending");

                    b.ToTable("outbox_messages", "requests");
                });

            modelBuilder.Entity("CivicOps.Modules.Requests.Infrastructure.Persistence.ProtocolSequence", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.HasKey("TenantId", "Year");

                    b.ToTable("protocol_sequences", "requests", t =>
                        {
                            t.HasCheckConstraint("ck_protocol_sequences_last_value_positive", "last_value > 0");
                        });
                });

            modelBuilder.Entity("CivicOps.Modules.Requests.Infrastructure.Persistence.RequestAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_request_audit_event");

                    b.HasIndex("TenantId", "RequestId", "OccurredAtUtc")
                        .HasDatabaseName("ix_request_audit_tenant_request_occurred_at");

                    b.ToTable("request_audit", "requests");
                });

            modelBuilder.Entity("CivicOps.Modules.Requests.Infrastructure.Persistence.RequestIdempotencyRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_hash")
                        .IsFixedLength();

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.HasKey("TenantId", "Key");

                    b.HasIndex("TenantId", "RequestId")
                        .HasDatabaseName("ix_request_idempotency_tenant_request");

                    b.ToTable("request_idempotency", "requests");
                });

            modelBuilder.Entity("CivicOps.Modules.Requests.Domain.Requests.RequestComment", b =>
                {
                    b.HasOne("CivicOps.Modules.Requests.Domain.Requests.Request", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "RequestId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_request_comments_tenant_request");
                });
#pragma warning restore 612, 618
        }
    }
}
